[loggers]
root = INFO

[handlers]
console = INFO, console

[formatters]
console = %(asctime)s - %(levelname)s - %(message)s

[handler_console]
class = StreamHandler
formatter = console
args = (sys.stdout,)
level = DEBUG